<?php


/*
$host = '192.168.88.13';
$dbuser = 'SYY';
$dbpass = '39122222';
$dbname = 'SAC';
*/



//$host = 'BECKPALMX-HP\SQLEXPRESS';

$host = '192.168.88.40';
$dbuser = 'SYY';
$dbpass = '39122222';
$dbname = 'SAC';


/*
$host = 'SAC-SHINEIT\MSSQLEXPRESS';
$dbuser = 'sa';
$dbpass = 'sadmin';
$dbname = 'SAC';
*/

/*

$host = '192.168.39.13';
$dbuser = 'SYY';
$dbpass = '39122222';
$dbname = 'SYY';

 */