<?php

// Dedicated and optimized query configuration for manage_wholesale_document

$select_query_sale = "
SELECT 
    DOCINFO.DI_REF,
    CONVERT(VARCHAR(10), DOCINFO.DI_DATE, 103) AS DI_DATE,
    CONVERT(VARCHAR(5), CAST(DOCINFO.DI_CRE_DATE AS DATETIME), 108) AS DI_TIME_CHK,
    DOCINFO.DI_ACTIVE,
    DOCTYPE.DT_DOCCODE,
    ARFILE.AR_CODE,
    ARFILE.AR_NAME,
    DEPTTAB.DEPT_CODE,
    DEPTTAB.DEPT_THAIDESC,
    ICCAT.ICCAT_CODE,
    ICCAT.ICCAT_NAME,
    SKUMASTER.SKU_CODE,
    SKUMASTER.SKU_NAME,
    SKUMASTER.SKU_E_NAME,
    BRAND.BRN_CODE,
    BRAND.BRN_NAME,
    TRANSTKD.TRD_QTY,
    TRANSTKD.TRD_Q_FREE,
    TRANSTKD.TRD_U_PRC,
    TRANSTKD.TRD_TDSC_KEYINV,
    TRANSTKD.TRD_B_AMT,
    SALESMAN.SLMN_CODE,
    SALESMAN.SLMN_NAME
FROM DOCINFO WITH (NOLOCK)
INNER JOIN DOCTYPE WITH (NOLOCK) ON DOCINFO.DI_DT = DOCTYPE.DT_KEY
INNER JOIN ARDETAIL WITH (NOLOCK) ON DOCINFO.DI_KEY = ARDETAIL.ARD_DI
INNER JOIN ARFILE WITH (NOLOCK) ON ARDETAIL.ARD_AR = ARFILE.AR_KEY
INNER JOIN TRANSTKH WITH (NOLOCK) ON DOCINFO.DI_KEY = TRANSTKH.TRH_DI
INNER JOIN TRANSTKD WITH (NOLOCK) ON TRANSTKH.TRH_KEY = TRANSTKD.TRD_TRH
INNER JOIN SKUMASTER WITH (NOLOCK) ON TRANSTKD.TRD_SKU = SKUMASTER.SKU_KEY
LEFT JOIN ICCAT WITH (NOLOCK) ON SKUMASTER.SKU_ICCAT = ICCAT.ICCAT_KEY
LEFT JOIN BRAND WITH (NOLOCK) ON SKUMASTER.SKU_BRN = BRAND.BRN_KEY
LEFT JOIN DEPTTAB WITH (NOLOCK) ON TRANSTKH.TRH_DEPT = DEPTTAB.DEPT_KEY
LEFT JOIN SLDETAIL WITH (NOLOCK) ON DOCINFO.DI_KEY = SLDETAIL.SLD_DI
LEFT JOIN SALESMAN WITH (NOLOCK) ON SLDETAIL.SLD_SLMN = SALESMAN.SLMN_KEY
";

$sql_cond_sale = " 
WHERE 
    DOCTYPE.DT_PROPERTIES = 307
    AND DOCINFO.DI_ACTIVE = 0
    AND (DOCTYPE.DT_DOCCODE IN ('IV00', 'DS00', 'CV00', 'CS00', 'IS', 'ISO') 
         OR DOCTYPE.DT_DOCCODE LIKE 'IS%' 
         OR DOCTYPE.DT_DOCCODE LIKE 'ISO%')
";

$sql_order_sale = " ORDER BY DOCINFO.DI_DATE DESC, DOCINFO.DI_CRE_DATE DESC, DOCINFO.DI_REF ";
