<?php
$select_query_customer = "
SELECT
 APCAT.APCAT_CODE,
 APCAT.APCAT_NAME,
 APFILE.AP_ENABLE,
 APFILE.AP_CODE,
 APFILE.AP_NAME,
 APFILE.AP_REMARK,
 APSUMMARY.APS_CRE_LIM,
 ACCOUNTCHART.AC_CODE,
 APFILE.AP_ACCESS,
 DEPTTAB.DEPT_CODE,
 APGL.APGL_CODE,
 APGL.APGL_NAME,
 APCONDITION.APCD_NAME,
 APCONDITION.APCD_TRADE_DC,
 APCONDITION.APCD_CASH_DC,
 APCONDITION.APCD_TERM,
 APCONDITION.APCD_APPRBCODE,
 ADDRBOOK.ADDB_COMPANY,
 ADDRBOOK.ADDB_BRANCH,
 ADDRBOOK.ADDB_TAX_ID,
 ADDRBOOK.ADDB_ADDB_1,
 ADDRBOOK.ADDB_ADDB_2,
 ADDRBOOK.ADDB_ADDB_3,
 ADDRBOOK.ADDB_PROVINCE,
 ADDRBOOK.ADDB_POST,
 ADDRBOOK.ADDB_PHONE,
 ADDRBOOK.ADDB_FAX,
 ADDRBOOK.ADDB_EMAIL
FROM APFILE WITH (NOLOCK)
JOIN APCAT WITH (NOLOCK) ON APCAT.APCAT_KEY = APFILE.AP_APCAT
JOIN APSUMMARY WITH (NOLOCK) ON APSUMMARY.APS_AP=APFILE.AP_KEY
JOIN ACCOUNTCHART WITH (NOLOCK) ON APFILE.AP_AC = ACCOUNTCHART.AC_KEY
JOIN DEPTTAB WITH (NOLOCK) ON APFILE.AP_DEPT = DEPTTAB.DEPT_KEY
JOIN APGL WITH (NOLOCK) ON APFILE.AP_APGL =APGL_KEY
JOIN APCONDITION WITH (NOLOCK) ON APFILE.AP_KEY = APCONDITION.APCD_AP
JOIN APADDRESS WITH (NOLOCK) ON APFILE.AP_KEY = APADDRESS.APA_AP
JOIN ADDRBOOK WITH (NOLOCK) ON APADDRESS.APA_ADDB = ADDRBOOK.ADDB_KEY ";

$select_query_customer_cond = "
WHERE AP_KEY >= 0
AND (APCONDITION.APCD_DEFAULT='Y')
AND APADDRESS.APA_DEFAULT = 'Y'";

$select_query_customer_order = " 
ORDER BY
APCAT.APCAT_CODE  ASC,
APFILE.AP_CODE ASC ";

