<?php

// Dedicated and optimized query configuration for wholesale documents & import cronjob (doc_info_wholesale_ks.php)

$select_query_sale = "
SELECT 
    DOCINFO.DI_KEY,
    DOCINFO.DI_REF,
    CONVERT(VARCHAR(10), DOCINFO.DI_DATE, 103) AS DI_DATE,
    CONVERT(VARCHAR(5), CAST(DOCINFO.DI_CRE_DATE AS DATETIME), 108) AS DI_TIME_CHK,
    MONTH(DOCINFO.DI_DATE) AS DI_MONTH,
    YEAR(DOCINFO.DI_DATE) AS DI_YEAR,
    DOCINFO.DI_ACTIVE,
    DOCTYPE.DT_DOCCODE,
    DOCTYPE.DT_PROPERTIES,
    ARFILE.AR_CODE,
    ARFILE.AR_NAME,
    ARDETAIL.ARD_B_AMT AS AROE_B_AMT,
    ARDETAIL.ARD_B_VAT,
    ARDETAIL.ARD_B_SV,
    ARDETAIL.ARD_B_SNV,
    ARDETAIL.ARD_TDSC_KEYIN,
    ARDETAIL.ARD_TDSC_KEYINV,
    ARDETAIL.ARD_G_VAT,
    ARDETAIL.ARD_G_SV,
    ARDETAIL.ARD_G_SNV,
    ARDETAIL.ARD_G_KEYIN,
    ARDETAIL.ARD_DUE_DA,
    ARDETAIL.ARD_CRNCYCODE,
    ARDETAIL.ARD_XCHG,
    SALESMAN.SLMN_CODE,
    SALESMAN.SLMN_NAME,
    TRANSTKH.TRH_REFER_XREF,
    TRANSTKH.TRH_REFER_IREF,
    TRANSTKH.TRH_REFER_PERSON,
    TRANSTKH.TRH_REFER_XTRA1,
    TRANSTKH.TRH_REFER_XTRA2,
    TRANSTKH.TRH_SHIP_DATE,
    TRANSTKH.TRH_VAT_TY,
    TRANSTKH.TRH_VAT_R,
    TRANSTKH.TRH_VATIO,
    TRANSTKH.TRH_N_ITEMS,
    TRANSTKH.TRH_N_QTY,
    DEPTTAB.DEPT_CODE,
    DEPTTAB.DEPT_THAIDESC,
    DEPTTAB.DEPT_ENGDESC,
    ICCAT.ICCAT_CODE,
    ICCAT.ICCAT_NAME,
    TRANSTKD.TRD_SEQ,
    SKUMASTER.SKU_CODE,
    SKUMASTER.SKU_NAME,
    SKUMASTER.SKU_E_NAME,
    TRANSTKD.TRD_VAT_TY,
    TRANSTKD.TRD_VAT,
    TRANSTKD.TRD_VAT_R,
    TRANSTKD.TRD_LOT_NO,
    TRANSTKD.TRD_SERIAL,
    TRANSTKD.TRD_SH_CODE,
    TRANSTKD.TRD_SH_NAME,
    BRAND.BRN_CODE,
    BRAND.BRN_NAME,
    TRANSTKD.TRD_QTY,
    TRANSTKD.TRD_Q_FREE,
    TRANSTKD.TRD_UTQNAME,
    TRANSTKD.TRD_UTQQTY,
    TRANSTKD.TRD_K_U_PRC,
    TRANSTKD.TRD_U_PRC,
    TRANSTKD.TRD_U_VATIO,
    TRANSTKD.TRD_B_UPRC,
    TRANSTKD.TRD_DSC_KEYIN,
    TRANSTKD.TRD_DSC_KEYINV,
    TRANSTKD.TRD_G_AMT,
    TRANSTKD.TRD_G_KEYIN,
    TRANSTKD.TRD_G_SELL,
    TRANSTKD.TRD_G_VAT,
    TRANSTKD.TRD_TDSC_KEYINV,
    TRANSTKD.TRD_B_SELL,
    TRANSTKD.TRD_B_VAT,
    TRANSTKD.TRD_B_AMT
FROM DOCINFO WITH (NOLOCK)
INNER JOIN DOCTYPE WITH (NOLOCK) ON DOCINFO.DI_DT = DOCTYPE.DT_KEY
INNER JOIN ARDETAIL WITH (NOLOCK) ON DOCINFO.DI_KEY = ARDETAIL.ARD_DI
INNER JOIN ARFILE WITH (NOLOCK) ON ARDETAIL.ARD_AR = ARFILE.AR_KEY
INNER JOIN TRANSTKH WITH (NOLOCK) ON DOCINFO.DI_KEY = TRANSTKH.TRH_DI
INNER JOIN TRANSTKD WITH (NOLOCK) ON TRANSTKH.TRH_KEY = TRANSTKD.TRD_TRH
INNER JOIN SKUMASTER WITH (NOLOCK) ON TRANSTKD.TRD_SKU = SKUMASTER.SKU_KEY
LEFT JOIN ICCAT WITH (NOLOCK) ON SKUMASTER.SKU_ICCAT = ICCAT.ICCAT_KEY
LEFT JOIN BRAND WITH (NOLOCK) ON SKUMASTER.SKU_BRN = BRAND.BRN_KEY
LEFT JOIN DEPTTAB WITH (NOLOCK) ON TRANSTKH.TRH_DEPT = DEPTTAB.DEPT_KEY
LEFT JOIN SLDETAIL WITH (NOLOCK) ON DOCINFO.DI_KEY = SLDETAIL.SLD_DI
LEFT JOIN SALESMAN WITH (NOLOCK) ON SLDETAIL.SLD_SLMN = SALESMAN.SLMN_KEY
";

$sql_cond_sale = " WHERE DOCINFO.DI_ACTIVE = 0 AND (DOCTYPE.DT_DOCCODE IN ('IV00', 'DS00', 'CV00', 'CS00', 'IS', 'ISO')) ";

$sql_order_sale = " ORDER BY DOCINFO.DI_DATE DESC, DOCINFO.DI_CRE_DATE DESC, DOCINFO.DI_REF ";