-- ----------------------------
-- Table structure for ims_product_sale_syy_ks
-- ----------------------------
DROP TABLE IF EXISTS `ims_product_sale_syy_ks`;
CREATE TABLE `ims_product_sale_syy_ks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `DI_KEY` int(11) DEFAULT NULL,
  `DI_REF` varchar(100) DEFAULT NULL,
  `DI_DATE` varchar(20) DEFAULT NULL,
  `DI_TIME_CHK` varchar(20) DEFAULT NULL,
  `DI_MONTH` int(11) DEFAULT NULL,
  `DI_MONTH_NAME` varchar(50) DEFAULT NULL,
  `DI_YEAR` int(11) DEFAULT NULL,
  `DI_ACTIVE` int(11) DEFAULT 0,
  `DT_DOCCODE` varchar(50) DEFAULT NULL,
  `DT_PROPERTIES` int(11) DEFAULT NULL,
  `AR_CODE` varchar(100) DEFAULT NULL,
  `AR_NAME` varchar(255) DEFAULT NULL,
  `AROE_B_AMT` decimal(15,2) DEFAULT 0.00,
  `ARD_B_VAT` decimal(15,2) DEFAULT 0.00,
  `ARD_B_SV` decimal(15,2) DEFAULT 0.00,
  `ARD_B_SNV` decimal(15,2) DEFAULT 0.00,
  `ARD_TDSC_KEYIN` decimal(15,2) DEFAULT 0.00,
  `ARD_TDSC_KEYINV` decimal(15,2) DEFAULT 0.00,
  `ARD_G_VAT` decimal(15,2) DEFAULT 0.00,
  `ARD_G_SV` decimal(15,2) DEFAULT 0.00,
  `ARD_G_SNV` decimal(15,2) DEFAULT 0.00,
  `ARD_G_KEYIN` decimal(15,2) DEFAULT 0.00,
  `ARD_DUE_DA` varchar(50) DEFAULT NULL,
  `ARD_CRNCYCODE` varchar(20) DEFAULT NULL,
  `ARD_XCHG` decimal(15,2) DEFAULT 1.00,
  `SLMN_CODE` varchar(100) DEFAULT NULL,
  `SLMN_NAME` varchar(255) DEFAULT NULL,
  `TRH_REFER_XREF` varchar(255) DEFAULT NULL,
  `TRH_REFER_IREF` varchar(255) DEFAULT NULL,
  `TRH_REFER_PERSON` varchar(255) DEFAULT NULL,
  `TRH_REFER_XTRA1` varchar(255) DEFAULT NULL,
  `TRH_REFER_XTRA2` varchar(255) DEFAULT NULL,
  `TRH_SHIP_DATE` varchar(50) DEFAULT NULL,
  `TRH_VAT_TY` int(11) DEFAULT NULL,
  `TRH_VAT_R` decimal(15,2) DEFAULT 0.00,
  `TRH_VATIO` int(11) DEFAULT NULL,
  `TRH_N_ITEMS` int(11) DEFAULT 0,
  `TRH_N_QTY` decimal(15,2) DEFAULT 0.00,
  `DEPT_CODE` varchar(100) DEFAULT NULL,
  `DEPT_THAIDESC` varchar(255) DEFAULT NULL,
  `DEPT_ENGDESC` varchar(255) DEFAULT NULL,
  `PRJ_CODE` varchar(100) DEFAULT NULL,
  `PRJ_NAME` varchar(255) DEFAULT NULL,
  `ICCAT_CODE` varchar(100) DEFAULT NULL,
  `ICCAT_NAME` varchar(255) DEFAULT NULL,
  `TRD_SEQ` int(11) DEFAULT 0,
  `SKU_CODE` varchar(100) DEFAULT NULL,
  `SKU_NAME` varchar(255) DEFAULT NULL,
  `SKU_E_NAME` varchar(255) DEFAULT NULL,
  `UTQ_NAME` varchar(100) DEFAULT NULL,
  `UTQ_QTY` decimal(15,2) DEFAULT 0.00,
  `GOODS_CODE` varchar(100) DEFAULT NULL,
  `TRD_VAT_TY` int(11) DEFAULT NULL,
  `TRD_VAT` decimal(15,2) DEFAULT 0.00,
  `TRD_VAT_R` decimal(15,2) DEFAULT 0.00,
  `TRD_LOT_NO` varchar(100) DEFAULT NULL,
  `TRD_SERIAL` varchar(100) DEFAULT NULL,
  `TRD_SH_CODE` varchar(100) DEFAULT NULL,
  `TRD_SH_NAME` varchar(255) DEFAULT NULL,
  `BRN_CODE` varchar(100) DEFAULT NULL,
  `BRN_NAME` varchar(255) DEFAULT NULL,
  `TRD_QTY` decimal(15,2) DEFAULT 0.00,
  `TRD_Q_FREE` decimal(15,2) DEFAULT 0.00,
  `TRD_UTQNAME` varchar(100) DEFAULT NULL,
  `TRD_UTQQTY` decimal(15,2) DEFAULT 0.00,
  `TRD_K_U_PRC` decimal(15,2) DEFAULT 0.00,
  `TRD_U_PRC` decimal(15,2) DEFAULT 0.00,
  `TRD_U_VATIO` int(11) DEFAULT NULL,
  `TRD_B_UPRC` decimal(15,2) DEFAULT 0.00,
  `TRD_DSC_KEYIN` decimal(15,2) DEFAULT 0.00,
  `TRD_DSC_KEYINV` decimal(15,2) DEFAULT 0.00,
  `TRD_G_AMT` decimal(15,2) DEFAULT 0.00,
  `TRD_G_KEYIN` decimal(15,2) DEFAULT 0.00,
  `TRD_G_SELL` decimal(15,2) DEFAULT 0.00,
  `TRD_G_VAT` decimal(15,2) DEFAULT 0.00,
  `TRD_TDSC_KEYINV` decimal(15,2) DEFAULT 0.00,
  `TRD_B_SELL` decimal(15,2) DEFAULT 0.00,
  `TRD_B_VAT` decimal(15,2) DEFAULT 0.00,
  `TRD_B_AMT` decimal(15,2) DEFAULT 0.00,
  `WL_CODE` varchar(100) DEFAULT NULL,
  `WH_CODE` varchar(100) DEFAULT NULL,
  `ARCD_NAME` varchar(255) DEFAULT NULL,
  `BRANCH` varchar(100) DEFAULT NULL,
  `PGROUP` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_doc_ref_seq` (`DI_KEY`, `DI_REF`, `DI_DATE`, `DT_DOCCODE`, `TRD_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
